### ISSUE TITLE
load_environmental_variables can't find .env file

### ISSUE THREAD

**Issue by rdmolony** [codema-dev/tasks#2]
When calling:
```yaml
on_render: codema_dev_tasks.hooks.load_environmental_variables
tasks:
  - source: codema_dev_tasks.requests.fetch_file
    name: download_buildings
    params:
      url: s3://codema-dev/dublin_census_2016_filled_with_ber_public_14_05_2021.parquet
    product: data/external/dublin_census_2016_filled_with_ber_public_14_05_2021.parquet
```
it isn't possible to find the `.env` file as `load_environmental_variables` searches the `codema_dev_tasks` source code and not the cwd of the user calling it
